version: '3.8'            # Version 3.8 is quite new and should work

services:
  todo-Frontend:          # The name of the service, can be anything
    image: todo-frontend  # Declares which image to use
    build: .              # Declares where to build if image is not found
    ports:                # Declares the ports to publish
      - 3001:3001
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3000/

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - todo-Frontend # wait for the frontend container to be started