version: '3.8'

services:
    library-backend:
      image: library-frontend-dev
      build:
        context: .
        dockerfile: Dockerfile.dev
      ports:
        - 3000:3000
      volumes:
        - ./:/usr/src/app