version: '3.8'

services:
    library-backend:
      image: library-backend-dev
      build:
        context: .
        dockerfile: Dockerfile.dev
      ports:
        - 4000:4000
      volumes:
        - ./:/app