

services:
    library-backend:
      image: library-backend-dev
      build:
        context: .
        dockerfile: Dockerfile.dev
      ports:
        - 4000:4000
      volumes:
        - ./library-backend:/app

    library-frontend:
      image: library-frontend-dev
      build:
        context: .
        dockerfile: Dockerfile.dev
      ports:
        - 3000:3000
      volumes:
        - ./library-frontend:/usr/src/app

        